# generated by datamodel-codegen:
#   filename:  oca.schema.json
#   timestamp: 2026-10-08T06:29:51+00:00

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, Field, constr


class Header(BaseModel):
    version: constr(pattern=r'^\d+\.\d+$') = Field(..., description='OCIS Version')
    generator: str = Field(
        ..., description='Name of the software that created this file'
    )
    timestamp: AwareDatetime | None = None


class Metadata(BaseModel):
    uuid: UUID
    assembly_name: str | None = None


class Instance(BaseModel):
    id: str = Field(..., description='Unique ID for this instance')
    source_uri: str = Field(
        ..., description='Relative or absolute path to the .ocp or .oce file'
    )
    transform: list[float] | None = Field(
        None,
        description='16-element 4x4 Transformation Matrix',
        max_length=16,
        min_length=16,
    )


class Type(Enum):
    MATE = 'MATE'
    ALIGN = 'ALIGN'
    OFFSET = 'OFFSET'
    FIXED = 'FIXED'


class Constraint(BaseModel):
    type: Type
    target_a: str
    target_b: str


class OpencadAssemblyDefinitionOca(BaseModel):
    header: Header
    metadata: Metadata
    instances: list[Instance]
    constraints: list[Constraint]
