# generated by datamodel-codegen:
#   filename:  oce.schema.json
#   timestamp: 2026-10-08T06:29:52+00:00

from __future__ import annotations

from uuid import UUID

from pydantic import AwareDatetime, BaseModel, Field, constr


class Header(BaseModel):
    version: constr(pattern=r'^\d+\.\d+$') = Field(..., description='OCIS Version')
    generator: str = Field(
        ..., description='Name of the software that created this file'
    )
    timestamp: AwareDatetime | None = None


class Metadata(BaseModel):
    uuid: UUID
    board_name: str | None = None


class Component(BaseModel):
    ref_des: str = Field(..., description='Reference Designator e.g., R1, U2')
    part_number: str
    footprint: str | None = None


class Net(BaseModel):
    name: str = Field(..., description='e.g., GND, 5V, MISO')
    nodes: list[str]


class OpencadElectricalDefinitionOce(BaseModel):
    header: Header
    metadata: Metadata
    components: list[Component]
    nets: list[Net]
