# generated by datamodel-codegen:
#   filename:  ocp.schema.json
#   timestamp: 2026-10-08T06:29:45+00:00

from __future__ import annotations

from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, Field, constr


class Header(BaseModel):
    version: constr(pattern=r'^\d+\.\d+$') = Field(..., description='OCIS Version')
    generator: str = Field(
        ..., description='Name of the software that created this file'
    )
    timestamp: AwareDatetime | None = None


class Units(Enum):
    mm = 'mm'
    cm = 'cm'
    m = 'm'
    in_ = 'in'
    ft = 'ft'


class Metadata(BaseModel):
    uuid: UUID
    name: str | None = None
    material: str | None = None
    units: Units


class Type(Enum):
    EXTRUDE = 'EXTRUDE'
    REVOLVE = 'REVOLVE'
    FILLET = 'FILLET'
    CHAMFER = 'CHAMFER'
    BOOLEAN = 'BOOLEAN'
    SKETCH = 'SKETCH'


class UctItem(BaseModel):
    op_id: str
    type: Type
    params: dict[str, Any]


class OpencadPartDefinitionOcp(BaseModel):
    header: Header
    metadata: Metadata
    uct: list[UctItem] = Field(
        ...,
        description='Ordered list of parametric operations.',
        title='Unified Change Tree',
    )
