# generated by datamodel-codegen:
#   filename:  ocr.schema.json
#   timestamp: 2026-10-08T06:29:53+00:00

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, Field, constr


class Header(BaseModel):
    version: constr(pattern=r'^\d+\.\d+$') = Field(..., description='OCIS Version')
    generator: str = Field(..., description='Solver that generated the result')
    timestamp: AwareDatetime | None = None


class Metadata(BaseModel):
    uuid: UUID
    source_sim: str = Field(..., description='URI to the .ocs file that generated this')


class Buffer(BaseModel):
    uri: str = Field(
        ..., description='Path to the .bin file (or base64 encoded string)'
    )
    byteLength: int


class ComponentType(Enum):
    FLOAT32 = 'FLOAT32'
    FLOAT64 = 'FLOAT64'
    UINT32 = 'UINT32'


class Type(Enum):
    SCALAR = 'SCALAR'
    VEC3 = 'VEC3'
    VEC4 = 'VEC4'
    MAT3 = 'MAT3'
    MAT4 = 'MAT4'


class BufferView(BaseModel):
    buffer: int = Field(..., description='Index of the buffer')
    byteOffset: int
    byteLength: int
    componentType: ComponentType
    type: Type
    name: str | None = None


class ElementType(Enum):
    TETRA4 = 'TETRA4'
    HEXA8 = 'HEXA8'
    TRI3 = 'TRI3'
    QUAD4 = 'QUAD4'


class Mesh(BaseModel):
    nodes: int = Field(
        ..., description='Index of the bufferView containing XYZ coordinates'
    )
    elements: int = Field(
        ..., description='Index of the bufferView containing node connectivity'
    )
    element_type: ElementType | None = None


class Domain(Enum):
    NODE = 'NODE'
    ELEMENT = 'ELEMENT'


class FieldModel(BaseModel):
    name: str = Field(..., description="e.g., 'Von_Mises_Stress', 'Displacement'")
    domain: Domain
    step: float | None = Field(
        None, description='Time step or frequency for this specific field data'
    )
    data: int = Field(
        ..., description='Index of the bufferView containing the result values'
    )


class OpencadResultDefinitionOcr(BaseModel):
    header: Header
    metadata: Metadata
    buffers: list[Buffer] = Field(
        ...,
        description='Array of raw binary files containing the heavy float/int arrays.',
    )
    bufferViews: list[BufferView] = Field(
        ...,
        description='Defines how to read the buffers (e.g., read 1000 floats starting at byte 0).',
    )
    mesh: Mesh
    fields: list[FieldModel] = Field(
        ..., description='The actual simulation results (e.g., Stress, Displacement).'
    )
