# generated by datamodel-codegen:
#   filename:  ocs.schema.json
#   timestamp: 2026-10-08T06:29:55+00:00

from __future__ import annotations

from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, Field, constr


class Header(BaseModel):
    version: constr(pattern=r'^\d+\.\d+$') = Field(..., description='OCIS Version')
    generator: str = Field(
        ..., description='Name of the software that created this file'
    )
    timestamp: AwareDatetime | None = None


class SimType(Enum):
    FEA_STATIC = 'FEA_STATIC'
    FEA_DYNAMIC = 'FEA_DYNAMIC'
    CFD_STEADY = 'CFD_STEADY'
    CFD_TRANSIENT = 'CFD_TRANSIENT'
    THERMAL = 'THERMAL'


class Metadata(BaseModel):
    uuid: UUID
    name: str | None = None
    sim_type: SimType


class Target(BaseModel):
    source_uri: str = Field(..., description='URI to the .oca or .ocp file')
    configuration: str | None = Field(
        None, description='Optional assembly state/configuration name'
    )


class ElementType(Enum):
    TETRA = 'TETRA'
    HEXA = 'HEXA'
    POLY = 'POLY'


class Mesh(BaseModel):
    global_size: float | None = None
    element_type: ElementType | None = None


class Type(Enum):
    FIXED = 'FIXED'
    PINNED = 'PINNED'
    SYMMETRY = 'SYMMETRY'
    WALL_NO_SLIP = 'WALL_NO_SLIP'
    VELOCITY_INLET = 'VELOCITY_INLET'
    PRESSURE_OUTLET = 'PRESSURE_OUTLET'


class BoundaryCondition(BaseModel):
    id: str
    type: Type
    target_entity: str = Field(..., description='Instance/Face ID from the target file')
    params: dict[str, Any] | None = None


class Type1(Enum):
    FORCE = 'FORCE'
    PRESSURE = 'PRESSURE'
    GRAVITY = 'GRAVITY'
    TEMPERATURE = 'TEMPERATURE'
    HEAT_FLUX = 'HEAT_FLUX'


class Load(BaseModel):
    id: str
    type: Type1
    target_entity: str
    vector: list[float] | None = None
    magnitude: float | None = None


class Setup(BaseModel):
    mesh: Mesh | None = None
    boundary_conditions: list[BoundaryCondition] | None = None
    loads: list[Load] | None = None


class Status(Enum):
    UNSOLVED = 'UNSOLVED'
    SOLVED = 'SOLVED'
    FAILED = 'FAILED'


class Results(BaseModel):
    status: Status | None = None
    data_uri: str | None = Field(
        None, description='Path to .vtk, .h5, or other result format'
    )


class OpencadSimulationDefinitionOcs(BaseModel):
    header: Header
    metadata: Metadata
    target: Target = Field(..., description='The geometric model to be simulated.')
    setup: Setup
    results: Results | None = Field(
        None, description='Pointers to heavy result data files generated by solvers.'
    )
